### PR TITLE
word-to-dtbook: propagate change of pagination possible values

### PR DESCRIPTION
**Pull request by NPavie**
@bertfrees A quick PR to propagate the change of pagination possible values of the script to the xslts.

### CODE REVIEW

**Comment by bertfrees** [comment]
@NPavie I wish you would have asked me about the bug first. I had solved it differently, but for some reason it got lost in a rebase and it wasn't included in the 9f7c1b222d836fbd1ae989fae7691c049df3e613 commit.

Your solution is fine too of course.

**Comment by bertfrees** [comment]
Here is how I did it: https://github.com/daisy/pipeline/commit/2a498f9ac89b8ab1c57be604d81f1ee1e5422b5e

**Comment by NPavie** [comment]
> I wish you would have asked me about the bug first, before spending time on it

It took me about 5 minutes , PR opening included, after checking the commits log so not much time lost here ^^

For the solution you propose, are you sure you want to keep 2 versions of the possible values between the xslts and the xproc script ?
If we change the possible values' top definition, I personally prefer to propagate the change to avoid possible mismatch later.

**Comment by bertfrees** [comment]
> It took me about 5 minutes

Hehe, OK then :-)

> If we change the possible values' top definition, I personally prefer to propagate the change to avoid possible mismatch later.

OK sure.

**Comment by bertfrees** [comment]
Merged in 0b65d802 (fixed up and force-pushed).

**Pull request closed without merging**
